apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: a100-spot
spec:
  priorities:
  - gpu:
      type: nvidia-tesla-a100
      count: 2
    spot: true
  nodePoolAutoCreation:
    enabled: true
  whenUnsatisfiable: DoNotScaleUp
